# Generated by Django 4.1 on 2022-10-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
