# Generated by Django 4.1 on 2022-10-27 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonPrintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_print_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KomponenKalkulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilowatt_hour', models.FloatField(default=0)),
                ('fuel_type', models.CharField(max_length=10)),
                ('kilometer_jarak', models.FloatField(default=1)),
                ('litre_per_km', models.FloatField(default=1.2)),
            ],
        ),
        migrations.CreateModel(
            name='UserTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_logged_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateField(default=django.utils.timezone.now)),
                ('usage', models.CharField(max_length=10)),
                ('carbon_print_kendaraan', models.FloatField()),
                ('histori_karbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalkulator.carbonprinthistory')),
            ],
        ),
    ]
