# Generated by Django 4.1 on 2022-10-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponenkalkulator',
            name='tagihan_listrik_rupiah',
            field=models.IntegerField(default=0),
        ),
    ]
