# Generated by Django 4.1 on 2022-10-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0003_rename_carbon_print_kendaraan_carbondetail_carbon_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbondetail',
            name='komponen_kalkulasi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kalkulator.komponenkalkulator'),
        ),
    ]
