# Generated by Django 4.1 on 2022-10-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0004_carbondetail_komponen_kalkulasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponenkalkulator',
            name='fuel_type',
            field=models.CharField(choices=[('bensin', 'Bensin'), ('diesel', 'Diesel')], max_length=10),
        ),
    ]
