# Generated by Django 4.1 on 2022-10-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('kalkulator', '0006_alter_komponenkalkulator_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komponenkalkulator',
            name='tagihan_listrik_rupiah',
        ),
        migrations.AddField(
            model_name='carbonprinthistory',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserTemp',
        ),
    ]
