# Generated by Django 4.1 on 2022-10-30 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonkendaraandarat',
            name='date_input',
            field=models.DateField(default=datetime.date(2022, 10, 30)),
        ),
        migrations.AlterField(
            model_name='carbonlistrik',
            name='date_input',
            field=models.DateField(default=datetime.date(2022, 10, 30)),
        ),
    ]
